name: '${name}'
version: '${version}'
main: me.xginko.snowballfight.SnowballFight
api-version: '1.13'
authors: [ xGinko ]
description: '${description}'
website: '${url}'
folia-supported: true

commands:
  snowballs:
    usage: /snowballs [ reload, version, disable ]
    description: admin commands

permissions:
  snowballs.cmd.disable:
    description: Disable the plugin
  snowballs.cmd.reload:
    description: Reload the plugin configuration
  snowballs.cmd.version:
    description: Show the plugin version